events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    upstream teleportal_backend {
        server web:5000;
    }

    server {
        listen 80;
        server_name localhost teleportal.ai;

        client_max_body_size 20M;

        location / {
            proxy_pass http://teleportal_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 120s;
        }

        location /static/ {
            proxy_pass http://teleportal_backend/static/;
            expires 7d;
            add_header Cache-Control "public, no-transform";
        }
    }
}